<?php

namespace App\Http\Controllers\Quotation;

use App\Http\Controllers\QuotationController;
use App\Models\Quotation;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Routing\Redirector;
use Inertia\Response;

class QuotationPartController extends QuotationController
{
    public function __construct()
    {
        $this->post_type_id = 1;
        $this->title = 'Part';
        $this->url = 'parts';
    }

    public function update($shipment, Request $request, Quotation $part): Redirector|RedirectResponse|Application
    {
        return parent::update($shipment, $request, $part); // TODO: Change the autogenerated stub
    }

    public function edit($shipment, Quotation $part): Response
    {
        return parent::edit($shipment, $part); // TODO: Change the autogenerated stub
    }

    public function show($shipment, Quotation $part)
    {
        return parent::show($shipment, $part); // TODO: Change the autogenerated stub
    }

    public function updatePhoto($shipment, Request $request, Quotation $part): RedirectResponse
    {
        return parent::updatePhoto($shipment, $request, $part); // TODO: Change the autogenerated stub
    }

    public function destroy($shipment, Quotation $part): RedirectResponse
    {
        return parent::destroy($shipment, $part); // TODO: Change the autogenerated stub
    }
}
