<?php

namespace App\Http\Controllers\Quotation;

use App\Http\Controllers\QuotationController;
use App\Models\Quotation;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Routing\Redirector;
use Inertia\Response;

class QuotationHygieneSikaController extends QuotationController
{
    public function __construct()
    {
        $this->post_type_id = 3;
        $this->title = 'Sika';
        $this->url = 'hygienes-sika';
    }

    public function update($shipment, Request $request, Quotation $hygienes_sika): Redirector|RedirectResponse|Application
    {
        return parent::update($shipment, $request, $hygienes_sika); // TODO: Change the autogenerated stub
    }

    public function edit($shipment, Quotation $hygienes_sika): Response
    {
        return parent::edit($shipment, $hygienes_sika); // TODO: Change the autogenerated stub
    }

    public function show($shipment, Quotation $hygienes_sika)
    {
        return parent::show($shipment, $hygienes_sika); // TODO: Change the autogenerated stub
    }

    public function updatePhoto($shipment, Request $request, Quotation $hygienes_sika): RedirectResponse
    {
        return parent::updatePhoto($shipment, $request, $hygienes_sika); // TODO: Change the autogenerated stub
    }

    public function destroy($shipment, Quotation $hygienes_sika): RedirectResponse
    {
        return parent::destroy($shipment, $hygienes_sika); // TODO: Change the autogenerated stub
    }
}
