<?php

namespace App\Http\Controllers\SaleOrder;

use App\Http\Controllers\SalesOrderController;
use App\Models\SalesOrder;
use Inertia\Response;

class SalesOrderHygieneRoserController extends SalesOrderController
{
    public function __construct()
    {
        $this->post_type_id = 4;
        $this->title = 'Roser';
        $this->url = 'hygienes-roser';
    }

    public function show($shipment, SalesOrder $sales_order_hygienes_roser): Response
    {
        return parent::show($shipment, $sales_order_hygienes_roser); // TODO: Change the autogenerated stub
    }

}
