<?php

namespace App\Http\Controllers\SaleOrder;

use App\Http\Controllers\SalesOrderController;
use App\Models\SalesOrder;
use Inertia\Response;

class SalesOrderHygieneSikaController extends SalesOrderController
{
    public function __construct()
    {
        $this->post_type_id = 3;
        $this->title = 'Sika';
        $this->url = 'hygienes-sika';
    }

    public function show($shipment, SalesOrder $sales_order_hygienes_sika): Response
    {
        return parent::show($shipment, $sales_order_hygienes_sika); // TODO: Change the autogenerated stub
    }

}
