<?php

namespace App\Http\Controllers\SaleOrder;

use App\Http\Controllers\SalesOrderController;
use App\Models\SalesOrder;
use Inertia\Response;

class SalesOrderHygieneVikanController extends SalesOrderController
{
    public function __construct()
    {
        $this->post_type_id = 2;
        $this->title = 'Vikan';
        $this->url = 'hygienes-vikan';
    }

    public function show($shipment, SalesOrder $sales_order_hygienes_vikan): Response
    {
        return parent::show($shipment, $sales_order_hygienes_vikan); // TODO: Change the autogenerated stub
    }

}
