<?php

namespace App\Http\Controllers\SaleOrder;

use App\Http\Controllers\SalesOrderController;
use App\Models\SalesOrder;
use Inertia\Response;

class SalesOrderPartController extends SalesOrderController
{
    public function __construct()
    {
        $this->post_type_id = 1;
        $this->title = 'Part';
        $this->url = 'parts';
    }

    public function show($shipment, SalesOrder $sales_order_part): Response
    {
        return parent::show($shipment, $sales_order_part); // TODO: Change the autogenerated stub
    }
}
